#!/usr/bin/env bash

# NAME
#	runc - compile & run C

# AUTHOR 
#	Francois "alco" Alcover

# DESCRIPTION 
#	Compiles and runs C source-file or code string 

# SYNOPSIS
#	runc SOURCE [ARGS]

# EXAMPLES
#	runc test.c
#	runc hello.c bob
#	runc 'printf("%s\n", "Hello bob!");'

#=====================================================

CCFLAGS="\
-std=c11 \
-lm \
-Wno-pedantic \
-Wno-unused-variable \
"

# no args, usage
if [ $# -eq 0 ]; then
    echo 'runc - compile and run C code'
    echo 'USAGE:    runc {FILE|STRING} [args]'
	echo 'EXAMPLE:  runc hello.c bob'
	echo "EXAMPLE:  runc 'printf(\"%s\n\", \"Hello bob!\");'"
    exit 1
fi

if [ -f "$1" ]; then

	src=$1
	exe="$src.runc.exe"
	shift
	args=$@

else

code="$1"
src='runc_generated.c'
exe='runc_generated.exe'

cat << EOF > "$src"
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <math.h>
#include <inttypes.h>
#include <complex.h>
#include <float.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include <locale.h>
#include <time.h>
#include <assert.h>
#include <errno.h>

int main (int argc, char **argv) {
$code
exit(EXIT_SUCCESS);
}
EOF

fi

gcc $CCFLAGS "$src" -o "$exe" && "./$exe" $args

exit 0