#!/usr/bin/env bash

# NAME
#	runc - compile and run C code

# AUTHOR 
#	Francois "alco" Alcover

# DESCRIPTION 
#	Compiles and runs C source-file or code string 

# SYNOPSIS
#	runc SOURCE [ARGS]

# EXAMPLES
#	runc test.c
#	runc hello.c Bob
#	runc 'printf("%s\n", "Hello Bob!");'

#=====================================================

CCFLAGS="\
-std=c11 \
-lm \
-lc \
-Wno-pedantic \
-Wno-unused-variable \
"

OUTDIR=/tmp/runc

# if no args, print usage
if [ $# -eq 0 ]; then
    echo 'runc - compile and run C code'
    echo 'USAGE:    runc {FILE|STRING} [args]'
	echo 'EXAMPLE:  runc hello.c Bob'
	echo "EXAMPLE:  runc 'printf(\"%s\n\", \"Hello Bob\");'"
    exit 1
fi

mkdir -p $OUTDIR

# source is a file
if [ -f "$1" ]; then

	src=$1
	exe="$OUTDIR/$(basename $src).exe"
	shift
	args=$@

else

# source is a string
code="$1"
src="$OUTDIR/gen.c"
exe="$OUTDIR/gen.exe"

cat << EOF > "$src"
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <math.h>
#include <inttypes.h>
#include <complex.h>
#include <float.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include <locale.h>
#include <time.h>
#include <assert.h>
#include <errno.h>

int main (int argc, char **argv) {
$code
exit(EXIT_SUCCESS);
}
EOF

fi

gcc $CCFLAGS "$src" -o "$exe" && "$exe" $args

exit 0